### ISSUE TITLE
Revamp roadmap

### ISSUE THREAD

**Issue by jaimergp** [conda/conda-standalone#35]
We've been doing some work in this repo to treat conda-standalone as a regular source repository that is packaged in conda-forge and defaults (instead of having in-feedstock source).

These are the pending tasks before we "cut" a distribution that will be packaged in the respective channels.

In-repo:
- [X] https://github.com/conda/conda-standalone/pull/25
- [X] https://github.com/conda/conda-standalone/pull/27
- [X] https://github.com/conda/conda-standalone/pull/28
- [X] https://github.com/conda/conda-standalone/pull/29
- [X] https://github.com/conda/conda-standalone/pull/30
- [X] https://github.com/conda/conda-standalone/pull/31
- [X] https://github.com/conda/conda-standalone/pull/32
- [X] https://github.com/conda/conda-standalone/pull/33
- [X] https://github.com/conda/conda-standalone/pull/38
- [X] https://github.com/conda/conda-standalone/releases/tag/23.7.2

Downstream:
- [x] https://github.com/conda/constructor/pull/711 - everything [passes](https://github.com/conda/constructor/actions/runs/5854213841) ✅ 

Packaging:

- [x] https://github.com/conda-forge/conda-standalone-feedstock/pull/60
- [x] `AnacondaRecipes` is pending

**Comment by jezdez** [comment]
@jaimergp Given that https://github.com/AnacondaRecipes/conda-standalone-feedstock exists now, can we close this as completed?

**Comment by jaimergp** [comment]
🚀 Thanks to everyone who helped!
